name: build with podman

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mgoltzsche/podman
    steps:
    - uses: actions/checkout@v4
    - run: podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
    - run: podman build --format docker -o artifacts -t ${{ env.IMAGE_NAME }} .
    - run: podman push ${{ env.IMAGE_NAME }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
