name: build with podman

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mgoltzsche/podman
      options: '--privileged'
    steps:
    - uses: actions/checkout@v4
    - run: ls -l
    #- run: podman login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
    #- run: podman build --format docker -o artifacts
    #- run: podman push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
